config/routes.rb
Rails.application.routes.draw do

  root 'contacts#index'

  get 'home/index'
  get 'home/about'
  get 'home/documentation'
  get 'home/quicklinks'

  devise_for :users
  resources :contacts

  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    #@contact = Contact.new
    @contact = current_user.contacts.build
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    #@contact = Contact.new(contact_params)
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @contact = current_user.contacts.find_by(id: params[:id])
    redirect_to contacts_path, notice: "Not Authorized To Edit This Contact" if @contact.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone, :instagram, :twitter, :facebook, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def documentation
  end

  def quicklinks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :instagram, class:"form-control", placeholder:"Instagram" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :facebook, class:"form-control", placeholder:"Facebook" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :contact_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <br/>

  <div class="actions">
    <%= form.submit class:"btn btn-info" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="card">
  <div class="card-header">
    <h4>Editing Contact</h4>
  </div>
  <div class="card-body">
    <%= render 'form', contact: @contact %>
    <br/>
    <%= link_to 'Show', @contact, class:"btn btn-info" %>
    <%= link_to 'Delete', @contact, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    <%= link_to 'Back', contacts_path, class:"btn btn-info" %>
  </div>
</div>

app/views/contacts/index.html.erb
<% if user_signed_in? %>
  <h2>Contact List</h2>
  <br/>

  <table class="table table-striped table-bordered table-hover table-responsive-sm">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Instagram</th>
        <th>Twitter</th>
        <th>Facebook</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
      <% if contact.user == current_user %>
          <tr>
            <td>
              <%= link_to contact.first_name + ' ' + contact.last_name, contact %>
            </td>
            <td><%= contact.email %></td>
            <td><%= contact.phone %></td>
            <td><%= contact.instagram %></td>
            <td><%= contact.twitter %></td>
            <td><%= contact.facebook %></td>
            <td><%= link_to 'Delete', contact, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to "New Contact", new_contact_path, class:"btn btn-info" %>
<% else %>
  <%= render file: "/home/index" %>
<% end %>

app/views/contacts/new.html.erb
<div class="card">
  <div class="card-header">
    <h4>Add New Contact</h4>
  </div>
  <div class="card-body">
    <%= render 'form', contact: @contact %>
    <br/>
    <%= link_to 'Back', contacts_path, class:"btn btn-info" %>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @contact.first_name %>  <%= @contact.last_name %></h1>
  
  <hr/>

  <p class="lead">
    <i class="fa fa-envelope"></i>&nbsp;&nbsp;<%= @contact.email %><br/>
    <i class="fa fa-phone" aria-hidden="true"></i>&nbsp;&nbsp;<%= @contact.phone %><br/>
    <i class="fa fa-instagram" aria-hidden="true"></i>&nbsp;&nbsp;<%= @contact.instagram %><br/>
    <i class="fa fa-twitter-square" aria-hidden="true"></i>&nbsp;&nbsp;<%= @contact.twitter %><br/>
    <i class="fa fa-facebook-official" aria-hidden="true"></i>&nbsp;&nbsp;<%= @contact.facebook %><br/>
  </p>

  <br/>
  
  <%= link_to 'Edit', edit_contact_path(@contact), class:"btn btn-info" %>
  
  <%= link_to 'Delete', @contact, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  
  <%= link_to 'Back', contacts_path, class:"btn btn-info" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
  <div class="container">
    <div class="navbar-brand">
      <div class="navbar-item title is-4">
          <%= link_to (raw("<i class='fa fa-address-book'></i> Contacts")), root_path, class:"navbar-brand" %>
      </div>
    </div>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item ctr-re">
            <%= link_to "Add Contact", new_contact_path, class:"nav-link" %>
          </li>

          <li class="nav-item ctr-re">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item ctr-re">
            <%= link_to "About", home_about_path, class:"nav-link" %>
          </li>
          
          <li class="nav-item ctr-re">
            <%= link_to "Documentation", home_documentation_path, class:"nav-link" %>
          </li>

          <li class="nav-item ctr-re">
            <%= link_to "Quick Links", home_quicklinks_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
   
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item nav-re">
            <%= link_to (raw("<b>Sign Out</b>")), destroy_user_session_path, method: :delete, class:"btn btn-outline-warning my-2 my-sm-0 nav-re" %>
          </li>
        <% else %>
          <li class="nav-item nav-re">
            <%= link_to (raw("<b>Sign Up</b>")), new_user_registration_path, class:"btn btn-outline-warning my-2 my-sm-0 nav-re" %>
          </li>

          <li class="nav-item nav-re">
            <%= link_to (raw("<b>Sign In</b>")), new_user_session_path, class:"btn btn-warning my-2 my-sm-0 ml-md-1 nav-re" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h2>About Us</h2>

<br/>

<div class="row">
    <div class="col-sm">

            <p>
                This web app is a Contact Management Tool to store your friend's or colleague's contact info including Email, phone number, Instagram, Twitter and Facebook. 
                With the Simple User Interface and Faster performance, we intend to provide a better service for our user.
                 Not only provide a better performance, we also provide a simple and better User Interface. 
                 Hence, it is easy to use this web app. It's self-explanatory.
            </p>
            <p>
                User can add, delete and update their list of contact details after Log In. 
                User can also update their account password or delete their account. 
                To create an account, user need to use their email.
                This web app is free to use. For any inquiries please contact aurellyagho25@gmail.com.
            </p>
    
 
    </div>
</div>

app/views/home/documentation.html.erb
<h2>Documentation</h2>
<br/>

<div class="card">
  <div class="card-header">
    <span class="badge badge-danger">Ruby</span>
    <span class="badge badge-warning">JavaScript</span>
    <span class="badge badge-info">Scss</span>
    <span class="badge badge-success">HTML</span>
  </div>
  <div class="card-body">
    <i class="fa fa-github" aria-hidden="true"></i>&nbsp;&nbsp;github.com/Aurellya/Contact-Book
    <br/><br/>
    <p>
        This sites is built using Ruby on Rails framework and Bootstrap. <br/>
        Go to my github to see more.
    </p>
    <br/>
    <a href="https://github.com/Aurellya/Contact-Book" class="btn btn-info">See More</a>
  </div>
</div>

app/views/home/index.html.erb
<h2>Contact Book</h2>
<br/>

<div class="row">
    <div class="col-sm">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Start Creating Your Own Contact Book</h5>
          <p class="card-text">
            Get started with &nbsp;<i class='fa fa-address-book'></i> Contacts. 
            The world’s simplest site to store the list of contact info of your friends, family or colleagues.
            </p><p>
            Just Sign Up using your email account.
            Login and Start creating your own contact book. Easy. Simple. Start Now!
          </p>
          <%= link_to "Start Now", new_user_session_path, class:"btn btn-info" %>
        </div>
      </div>
    </div>
    <div class="col-sm text-center">
      <img src="https://images.assetsdelivery.com/compings_v2/stockgiu/stockgiu1811/stockgiu181105120.jpg" width="380px"/>
    </div>
</div>

<br/><br/>

<div class="jumbotron">
  <div class="card-deck">
    <div class="card">
      <div class="text-center mt-md-4">
        <i class="fa fa-lock" aria-hidden="true" style="font-size: 44px"></i>
      </div>
      <div class="card-body">
        <h5 class="card-title text-center">Secure</h5>
        <p class="card-text text-center">
          This site is secure. All your password is encrypted and all your data is saved in the secure place. 
        </p>
      </div>
    </div>
    <div class="card">
        <div class="text-center mt-md-4">
          <i class="fa fa-lightbulb-o" aria-hidden="true" style="font-size: 44px"></i></i>
        </div>
          <div class="card-body">
          <h5 class="card-title text-center">Better Performance</h5>
          <p class="card-text text-center">
            Do not worry about performance. We provide you the best possible technical performance.
          </p>
        </div>
    </div>
    <div class="card">
        <div class="text-center mt-md-4">
            <i class="fa fa-user-o" aria-hidden="true" style="font-size: 44px"></i>
        </div>
        <div class="card-body">
        <h5 class="card-title text-center">Simple</h5>
        <p class="card-text text-center">
          We provide you with the simple interface. Easy to access, easy to start, and easy to use.
        </p>
        </div>
    </div>
  </div>
</div>

app/views/home/quicklinks.html.erb
<h2>Quick Links</h2>
<br/>
<i class="fa fa-envelope"></i>&nbsp;&nbsp;contactbook@gmail.com<br/>
<i class="fa fa-phone" aria-hidden="true"></i>&nbsp;&nbsp;4444 1234 9876<br/>
<i class="fa fa-instagram" aria-hidden="true"></i>&nbsp;&nbsp;contact_book<br/>
<i class="fa fa-twitter-square" aria-hidden="true"></i>&nbsp;&nbsp;@contactbook55<br/>
<i class="fa fa-facebook-official" aria-hidden="true"></i>&nbsp;&nbsp;Contact Book</i>

app/views/layouts/_alerts.html.erb
<div class="alert alert-dark alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Contact List</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  
    <%= render "home/header" %>

    <div class="container">
     <br/><br/>

      <% if notice%>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
      <br/><br/>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>